[package]
name = "enum-iterator-derive"
version = "0.5.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = "Procedural macro to iterate over the variants of a field-less enum"
license = "MIT"
homepage = "https://github.com/stephaneyfx/enum-iterator"
repository = "https://github.com/stephaneyfx/enum-iterator.git"
documentation = "https://docs.rs/enum-iterator-derive"
keywords = ["enum", "variants", "iterator"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.4"
quote = "1.0.2"
syn = "1.0.5"
