[package]
name = "enum-iterator"
version = "0.5.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = "Tools to iterate over the variants of a field-less enum"
license = "MIT"
homepage = "https://github.com/stephaneyfx/enum-iterator"
repository = "https://github.com/stephaneyfx/enum-iterator.git"
documentation = "https://docs.rs/enum-iterator"
keywords = ["enum", "variants", "iterator"]

[dependencies]
enum-iterator-derive = {path = "../enum-iterator-derive", version = "0.5.0"}
